# Generated by Django 2.1.4 on 2018-12-26 13:01

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('description', models.TextField(help_text='Enter a description for this Algorithm', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular course', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a description for this course', max_length=1000)),
                ('common_age_from', models.TimeField()),
                ('common_age_to', models.TimeField()),
                ('recommended_age_from', models.TimeField()),
                ('recommended_age_to', models.TimeField()),
                ('image', models.ImageField(help_text='Upload preview for this course', upload_to='')),
                ('algorithm', models.ForeignKey(help_text='Algorithm for pithing this course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Algorithm')),
            ],
        ),
        migrations.CreateModel(
            name='CourseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('ancestor_type', models.TextField(max_length=100)),
                ('image', models.ImageField(help_text='Upload preview for this CourseType', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a video genre', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a language', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular video', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a description of the video', max_length=1000)),
                ('duration', models.TimeField(max_length=13)),
                ('order', models.IntegerField(help_text='Order this lesson during course')),
                ('image', models.ImageField(help_text='Upload preview for this lesson', upload_to='')),
                ('varles_1', models.CharField(help_text='Reserved var for set up the algorithm.', max_length=50)),
                ('varles_2', models.CharField(help_text='Reserved var for set up the algorithm.', max_length=50)),
                ('varles_3', models.CharField(help_text='Reserved var for set up the algorithm.', max_length=50)),
                ('course', models.ForeignKey(help_text='Select course of this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Course')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language')),
            ],
        ),
        migrations.CreateModel(
            name='Logia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this logia. The videos for the same story but different producers', max_length=200)),
                ('description', models.TextField(help_text='Enter a description for this logia', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular producer', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a description of the producer', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Pupil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(help_text='Which user have this child', max_length=200)),
                ('name', models.CharField(help_text='Name of this child', max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Upload avatar for this pupil', upload_to='')),
                ('status', models.CharField(blank=True, choices=[('b', 'Boy'), ('g', 'Girl')], default='b', help_text="Choose pupil's gender", max_length=1)),
                ('completed_courses', models.ManyToManyField(to='catalog.Course')),
                ('current_lessons', models.ManyToManyField(to='catalog.Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of this serial', max_length=200)),
                ('description', models.TextField(help_text='Enter a description for this serial', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of technology: computer animation, drawed, e.t.c.', max_length=200)),
                ('description', models.TextField(help_text='Enter a description for this technology', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular video', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Enter a description of the video', max_length=1000)),
                ('duration', models.TimeField(max_length=13)),
                ('image', models.ImageField(help_text='Upload preview for video', upload_to='')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this video', to='catalog.Genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language')),
                ('logia', models.ForeignKey(help_text='Select a related logia for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Logia')),
                ('producer', models.ManyToManyField(help_text='Select a producer of this video', to='catalog.Producer')),
                ('serial', models.ForeignKey(help_text='Select a related serial for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Serial')),
                ('technology', models.ForeignKey(help_text='Select a related technology: computer animation, drawed, e.t.c.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Technology')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(help_text="It's quite enough to store only last course type cause all the chain can be restored automatically", null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CourseType'),
        ),
        migrations.AddField(
            model_name='course',
            name='producer',
            field=models.ManyToManyField(help_text='Select a producer of this course', to='catalog.Producer'),
        ),
    ]
