# Generated by Django 2.1.4 on 2018-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupil',
            name='planned_courses',
            field=models.ManyToManyField(related_name='planned_courses', to='catalog.Course'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='completed_courses',
            field=models.ManyToManyField(related_name='completed_courses', to='catalog.Course'),
        ),
    ]
