# Generated by Django 2.1.4 on 2018-12-26 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20181226_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
