# Generated by Django 2.1.4 on 2018-12-26 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20181226_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a country', max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='language',
            name='status',
            field=models.CharField(blank=True, choices=[('o', 'Official language'), ('r', 'Regional language')], default='o', help_text='Is this language official for this country or it regional', max_length=1),
        ),
        migrations.AddField(
            model_name='producer',
            name='status',
            field=models.CharField(blank=True, choices=[('e', 'Entertaining video'), ('l', 'Lessons'), ('b', 'Both')], default='e', help_text='Do you produce entertaining video, lessons video or both', max_length=1),
        ),
        migrations.AddField(
            model_name='pupil',
            name='native_language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AddField(
            model_name='language',
            name='country',
            field=models.ForeignKey(help_text='Related country for this language', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Country'),
        ),
        migrations.AddField(
            model_name='pupil',
            name='country',
            field=models.ForeignKey(help_text='Your country uses for defining official and regional languages in your location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Country'),
        ),
    ]
