# Generated by Django 2.1.4 on 2018-12-26 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20181226_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_language',
            field=models.BooleanField(default=False, help_text='Is this course for study language?'),
        ),
        migrations.AddField(
            model_name='course',
            name='target_language',
            field=models.ForeignKey(help_text='Select a target language, if this is language course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_language', to='catalog.Language'),
        ),
        migrations.AddField(
            model_name='course',
            name='teaching_language',
            field=models.ForeignKey(help_text='Select a language of teaching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_language', to='catalog.Language'),
        ),
    ]
