# Generated by Django 2.1.4 on 2018-12-27 11:06

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20181226_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetype',
            name='ancestor_type',
        ),
        migrations.AddField(
            model_name='coursetype',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='catalog.CourseType'),
        ),
    ]
