# Generated by Django 2.1.4 on 2018-12-27 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20181227_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='lft',
            field=models.IntegerField(default=0),
        ),
    ]
