# Generated by Django 2.1.4 on 2018-12-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20181227_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetype',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, editable=False),
        ),
    ]
