# Generated by Django 2.1.4 on 2018-12-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20181227_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursetype',
            name='image',
        ),
    ]
