# Generated by Django 2.1.4 on 2019-01-28 11:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0013_coursetype_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'permissions': (('can_create_course', 'Create course'), ('can_update_course', 'Update course'), ('can_delete_course', 'Delete course'))},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'permissions': (('can_upload_lesson', 'Upload lesson'), ('can_update_lesson', 'Update lesson'), ('can_delete_lesson', 'Delete lesson'))},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'permissions': (('can_upload_video', 'Upload video'), ('can_update_video', 'Update video'), ('can_delete_video', 'Delete video'))},
        ),
        migrations.RemoveField(
            model_name='pupil',
            name='user',
        ),
        migrations.AddField(
            model_name='pupil',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular lesson', primary_key=True, serialize=False),
        ),
    ]
