# Generated by Django 2.1.4 on 2019-01-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20190128_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='varles_1',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='varles_2',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='varles_3',
        ),
        migrations.AlterField(
            model_name='course',
            name='algorithm',
            field=models.ForeignKey(blank=True, help_text='Algorithm for pithing this course', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Algorithm'),
        ),
        migrations.AlterField(
            model_name='course',
            name='common_age_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='common_age_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.ForeignKey(blank=True, help_text="It's quite enough to store only last course type cause all the chain can be restored automatically", null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.CourseType'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description for this course', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload preview for this course', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_language',
            field=models.BooleanField(blank=True, default=False, help_text='Is this course for study language?', null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='producer',
            field=models.ManyToManyField(blank=True, help_text='Select a producer of this course', null=True, to='catalog.Producer'),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommended_age_from',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='recommended_age_to',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='target_language',
            field=models.ForeignKey(blank=True, help_text='Select a target language, if this is language course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_language', to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='course',
            name='teaching_language',
            field=models.ForeignKey(blank=True, help_text='Select a language of teaching', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teaching_language', to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='course',
            field=models.ForeignKey(blank=True, help_text='Select course of this lesson', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Course'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of the video', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.TimeField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload preview for this lesson', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.IntegerField(blank=True, help_text='Order this lesson during course', null=True),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='completed_courses', to='catalog.Course'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Your country uses for defining official and regional languages in your location', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Country'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='current_lessons',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.Lesson'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload avatar for this pupil', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='native_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='planned_courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='planned_courses', to='catalog.Course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(blank=True, help_text='Enter a description of the video', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.TimeField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this video', null=True, to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload preview for video', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='video',
            name='language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language'),
        ),
        migrations.AlterField(
            model_name='video',
            name='logia',
            field=models.ForeignKey(blank=True, help_text='Select a related logia for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Logia'),
        ),
        migrations.AlterField(
            model_name='video',
            name='producer',
            field=models.ManyToManyField(blank=True, help_text='Select a producer of this video', null=True, to='catalog.Producer'),
        ),
        migrations.AlterField(
            model_name='video',
            name='serial',
            field=models.ForeignKey(blank=True, help_text='Select a related serial for this video', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Serial'),
        ),
        migrations.AlterField(
            model_name='video',
            name='technology',
            field=models.ForeignKey(blank=True, help_text='Select a related technology: computer animation, drawed, e.t.c.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Technology'),
        ),
    ]
