# Generated by Django 2.1.4 on 2019-01-29 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_auto_20190129_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='language',
        ),
        migrations.AddField(
            model_name='lesson',
            name='path',
            field=models.URLField(blank=True, help_text='Set url path for this lesson'),
        ),
        migrations.AddField(
            model_name='video',
            name='path',
            field=models.URLField(blank=True, help_text='Set url path for this video'),
        ),
        migrations.AlterField(
            model_name='course',
            name='producer',
            field=models.ManyToManyField(blank=True, help_text='Select a producer of this course', to='catalog.Producer'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='completed_courses',
            field=models.ManyToManyField(blank=True, related_name='completed_courses', to='catalog.Course'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='current_lessons',
            field=models.ManyToManyField(blank=True, to='catalog.Lesson'),
        ),
        migrations.AlterField(
            model_name='pupil',
            name='planned_courses',
            field=models.ManyToManyField(blank=True, related_name='planned_courses', to='catalog.Course'),
        ),
        migrations.AlterField(
            model_name='video',
            name='genre',
            field=models.ManyToManyField(blank=True, help_text='Select a genre for this video', to='catalog.Genre'),
        ),
        migrations.AlterField(
            model_name='video',
            name='producer',
            field=models.ManyToManyField(blank=True, help_text='Select a producer of this video', to='catalog.Producer'),
        ),
    ]
